# Generated by Django 5.0.2 on 2024-03-02 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuarioempresapermission',
            name='usuario_empresa',
        ),
        migrations.RemoveField(
            model_name='usuarioempresapermission',
            name='permission',
        ),
        migrations.RemoveField(
            model_name='usuarioresponsavel',
            name='empresa',
        ),
        migrations.RemoveField(
            model_name='usuarioresponsavel',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='usuarioresponsavel',
            name='user_permissions',
        ),
        migrations.RemoveField(
            model_name='usuarioresponsavelpermission',
            name='usuario_empresa',
        ),
        migrations.RemoveField(
            model_name='usuarioresponsavelpermission',
            name='permission',
        ),
        migrations.DeleteModel(
            name='UsuarioEmpresa',
        ),
        migrations.DeleteModel(
            name='UsuarioEmpresaPermission',
        ),
        migrations.DeleteModel(
            name='UsuarioResponsavel',
        ),
        migrations.DeleteModel(
            name='UsuarioResponsavelPermission',
        ),
    ]
