# Generated by Django 5.0.2 on 2024-03-02 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_remove_usuarioempresapermission_usuario_empresa_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='cnpj',
            field=models.CharField(default='ksdjf', max_length=18),
            preserve_default=False,
        ),
    ]
