# Generated by Django 5.0.2 on 2024-03-02 18:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0005_alter_usuarioresponsavel_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='usuarioresponsavel',
            name='cpf',
            field=models.CharField(default=4200266148, max_length=14, unique=True, verbose_name='CPF'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='empresa',
            name='responsavel',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='empresa', to=settings.AUTH_USER_MODEL),
        ),
    ]
