# Generated by Django 5.0.2 on 2024-03-02 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0007_usuarioresponsavel_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuarioresponsavel',
            name='nome',
            field=models.CharField(default='albertao', max_length=100),
            preserve_default=False,
        ),
    ]
