# Generated by Django 5.0.2 on 2024-03-02 18:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0008_usuarioresponsavel_nome'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresa',
            name='responsavel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='empresa', to='usuarios.usuarioresponsavel'),
        ),
    ]
